FROM condaforge/miniforge3


WORKDIR /django_app


COPY environment.yml .
RUN conda env create -f environment.yml && conda clean --all -y


ENV PATH /opt/conda/envs/django_env/bin:$PATH


COPY . .


CMD ["celery", "-A", "mysite", "worker", "-l", "info"]

