# Generated by Django 4.2.19 on 2025-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_multiple_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
